import fs from "node:fs";
import path from "node:path";

/**
 * Prisma 7's generated client no longer exposes `relationFromFields` at
 * runtime (the old `Prisma.dmmf` is gone, and its replacement only carries
 * `{name, kind, type, relationName}` for relation fields). lib/entity-relations.ts
 * needs the actual FK column name to run delete-blocking-reference checks, so
 * this script parses prisma/schema.prisma directly — the same source of truth
 * Prisma itself used to derive relationFromFields from — and emits a static
 * manifest. Runs after `prisma generate` (see package.json) so it stays in
 * sync with the schema automatically; nothing here should be hand-maintained.
 */

const schemaPath = path.join(process.cwd(), "prisma/schema.prisma");
const outPath = path.join(process.cwd(), "generated/prisma-relations.ts");

const schema = fs.readFileSync(schemaPath, "utf8");

type SchemaRelation = {
  modelName: string;
  delegateName: string;
  fkField: string;
  targetModel: string;
  hasDeletedAt: boolean;
};

const relations: SchemaRelation[] = [];

const modelBlockRegex = /model\s+(\w+)\s*\{([\s\S]*?)\n\}/g;
const relationFieldRegex = /^\s*(\w+)\s+(\w+)\??\s*(?:\[\])?\s*@relation\(([^)]*)\)/;
const fieldsArgRegex = /fields:\s*\[([^\]]+)\]/;

let modelMatch: RegExpExecArray | null;
while ((modelMatch = modelBlockRegex.exec(schema))) {
  const [, modelName, body] = modelMatch;
  const hasDeletedAt = /^\s*deletedAt\s/m.test(body);
  const delegateName = modelName.charAt(0).toLowerCase() + modelName.slice(1);

  for (const line of body.split("\n")) {
    const fieldMatch = relationFieldRegex.exec(line);
    if (!fieldMatch) continue;

    const [, relationField, targetModel, relationArgs] = fieldMatch;
    const fieldsArgMatch = fieldsArgRegex.exec(relationArgs);
    if (!fieldsArgMatch) continue; // inverse/"many" side — no FK column on this model

    const fkFields = fieldsArgMatch[1].split(",").map((f) => f.trim());
    if (fkFields.length !== 1) {
      throw new Error(
        `generate-relations.ts only supports single-column foreign keys, found composite key on ${modelName}.${relationField}: [${fkFields.join(", ")}]`,
      );
    }

    relations.push({ modelName, delegateName, fkField: fkFields[0], targetModel, hasDeletedAt });
  }
}

const contents = `/* AUTO-GENERATED by scripts/generate-relations.ts from prisma/schema.prisma — do not edit directly. */

export type SchemaRelation = {
  modelName: string;
  delegateName: string;
  fkField: string;
  targetModel: string;
  hasDeletedAt: boolean;
};

export const SCHEMA_RELATIONS: SchemaRelation[] = ${JSON.stringify(relations, null, 2)};
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, contents);

console.log(`Generated ${relations.length} relation(s) -> ${path.relative(process.cwd(), outPath)}`);
